/**
 * Structured quantitative survey items for the indicators, keyed by id.
 * Authored to gold standard per category. The 5 originally-validated items
 * (aided-awareness, purchase-intention, jar-scales, van-westendorp, nps) live
 * in `./indicators-detail` and take precedence in the merge.
 */

import type { SurveyItem } from "./indicators";

export const INDICATOR_SURVEY: Record<string, SurveyItem[]> = {
  // ── Brand Health & Equity ────────────────────────────────────────────────
  "tom-awareness": [
    { type: "open_text", stem: "When you think about [category], which brand comes to mind first? Please type the first brand that comes to mind.", base: "All respondents", randomize: false, analysis: "Capture FIRST mention only; code verbatims to a brand list; % of respondents naming each brand = Top-of-Mind Awareness. Report client brand TOMA and rank vs. competitors.", placement: "Very first substantive question, before any brand names are shown (must precede aided/spontaneous awareness to avoid priming).", notes: "Single open field for first mention only; do NOT show any brand list. Spell-check/auto-code verbatims. Keep coding frame stable across waves." },
  ],
  "spontaneous-awareness": [
    { type: "open_text", stem: "Which other brands of [category] can you think of? Please list all the brands that come to mind, even if only by name.", base: "All respondents", randomize: false, analysis: "Record ALL mentions (combine with the TOM first mention); code verbatims to brand list; % mentioning each brand = spontaneous/unaided awareness.", placement: "Immediately after the Top-of-Mind question, still before any aided list is shown.", notes: "Provide multiple open lines/boxes to encourage recall. Net first-mention + subsequent mentions for total unaided. Never expose the brand list beforehand." },
  ],
  "brand-salience": [
    { type: "grid", stem: "Thinking about the situations below, which brand(s) of [category] would you associate with each one? Select all brands that come to mind for each situation.", attributes: ["When you want a treat or to reward yourself","For an everyday/routine occasion","When you are with family or friends","When you need something quickly / on the go","When looking for the best quality","When looking for the best value"], options: ["[Client brand]","[Competitor 1]","[Competitor 2]","[Competitor 3]","None of these"], base: "All respondents aware of at least one brand", randomize: true, analysis: "Pick-any association per category-entry-point (CEP). Per brand compute Mental Availability = mean association across CEPs, and share of associations vs. competitors. Report Mental Penetration (% associating brand with ≥1 CEP).", placement: "After awareness blocks; before the detailed image battery.", notes: "Ehrenberg-Bass CEP approach. Randomize CEP rows and brand columns. CEPs must be category-specific. 'None of these' exclusive per row." },
  ],
  "brand-familiarity": [
    { type: "single", stem: "How well do you know [brand]?", scalePoints: ["Know it very well","Know it fairly well","Know just a little about it","Know only the name","Never heard of it"], base: "All respondents (asked per brand for the brand set)", randomize: false, analysis: "% Top-2-Box ('Know very well' + 'Know fairly well') = familiarity. Track T2B over waves and vs. competitors.", placement: "After aided awareness, before image/consideration; loop across measured brands.", notes: "Order scale from most to least familiar consistently. Familiarity is distinct from awareness — do not collapse." },
  ],
  "brand-consideration": [
    { type: "multi", stem: "Which, if any, of the following brands of [category] would you consider buying the next time you are in the market for [category]?", options: ["[Client brand]","[Competitor 1]","[Competitor 2]","[Competitor 3]","[Competitor 4]","None of these"], base: "All respondents aware of at least one brand", randomize: true, analysis: "Pick-any: % selecting each brand = consideration. Consideration stage of the brand funnel (base for preference/usage conversion).", placement: "Awareness → Familiarity → Consideration order in the funnel block.", notes: "Pick-any maximizes the consideration set vs. forcing a scale; base must be brand-aware. 'None of these' exclusive." },
  ],
  "brand-preference": [
    { type: "single", stem: "And of the brands you would consider, which ONE would be your first choice the next time you are buying [category]?", options: ["[Client brand]","[Competitor 1]","[Competitor 2]","[Competitor 3]","[Competitor 4]"], base: "Respondents who would consider 2+ brands (set piped from consideration); single-consideration respondents auto-assigned.", randomize: true, analysis: "Forced single choice: % naming each brand = first-choice preference / preference share. Convert to preference-to-consideration ratio in the funnel.", placement: "Immediately after consideration; before purchase intention/pricing.", notes: "Pipe in only the brands the respondent said they would consider. One answer only; do not offer 'none'." },
  ],
  "brand-trial": [
    { type: "multi", stem: "Which, if any, of the following brands of [category] have you ever bought or used?", options: ["[Client brand]","[Competitor 1]","[Competitor 2]","[Competitor 3]","[Competitor 4]","None of these"], base: "All respondents aware of at least one brand", randomize: true, analysis: "Pick-any: % ever bought/used each brand = trial/penetration. Combine with awareness to compute trial conversion.", placement: "Usage block, after consideration/preference; before period-based usage.", notes: "'Ever used' = lifetime trial, distinct from current usage. 'None of these' exclusive." },
  ],
  "brand-usage": [
    { type: "grid", stem: "When did you last buy or use each of the following brands of [category]?", attributes: ["[Client brand]","[Competitor 1]","[Competitor 2]","[Competitor 3]","[Competitor 4]"], scalePoints: ["In the past 4 weeks","1–3 months ago","4–12 months ago","More than 12 months ago","Never used"], base: "All respondents aware of at least one brand.", randomize: true, analysis: "Recency grid → derive period users: P4W; P3M = past 4 weeks + 1–3 months; P12M = all within 12 months. % users per period per brand. Match reported period to category cycle.", placement: "After trial; core of the usage block.", notes: "A single recency question yields all period nets — cleaner than separate P4W/P3M/P12M items. Align headline period with category cycle (FMCG=P4W, durables=P12M)." },
  ],
  bumo: [
    { type: "single", stem: "Which ONE brand of [category] do you use or buy most often?", options: ["[Client brand]","[Competitor 1]","[Competitor 2]","[Competitor 3]","[Competitor 4]","Other (please specify)","No single brand / varies"], base: "Respondents who have used at least one brand in the category (category users).", randomize: true, analysis: "Single choice: % naming each brand = BUMO / main-brand share (proxy for volumetric share). BUMO retention = % keeping the same main brand across waves.", placement: "After period usage; anchors the 'main brand' for downstream loyalty/satisfaction loops.", notes: "Force a single answer; allow 'Other (specify)' and an explicit 'varies' code. Main-brand designation pipes into loyalty questions." },
  ],
  "brand-loyalty": [
    { type: "scale", stem: "How likely are you to continue using or buying [main brand] in the future?", scalePoints: ["Definitely will continue","Probably will continue","Might or might not","Probably will not continue","Definitely will not continue"], base: "Users of the brand (main-brand users / BUMO = brand); piped main brand.", randomize: false, analysis: "% Top-2-Box (intention to continue) = stated retention/loyalty. Triangulate with behavioural share-of-last-10-purchases and wave-on-wave BUMO retention.", placement: "Loyalty/relationship block, after BUMO; pair with a behavioural share-of-requirements item.", notes: "Stated continuation can over-state loyalty — validate against behavioural SOR ('of your last 10 purchases, how many were [brand]?') and observed BUMO retention." },
  ],
  "brand-advocacy": [
    { type: "scale", stem: "How likely are you to recommend [brand] to a friend or colleague?", scalePoints: ["0 — Not at all likely","1","2","3","4","5","6","7","8","9","10 — Extremely likely"], base: "Respondents familiar with / who have used the brand.", randomize: false, analysis: "NPS: Promoters (9–10) − Detractors (0–6), ignoring Passives (7–8). Report NPS and the full distribution; track vs. competitors.", placement: "Relationship/advocacy block, after satisfaction/loyalty.", notes: "Standard 0–10 Reichheld NPS. Keep 11-point scale and 0/10 anchoring exactly. Optionally follow with an open 'why'." },
  ],
  "brand-image": [
    { type: "grid", stem: "Which of the following brands do you associate with each statement below? Select all the brands that apply for each statement.", attributes: ["Is a brand for people like me","Offers high quality","Is good value for money","Is innovative / always improving","Is a brand I can trust","Is becoming more popular","Has a good reputation"], options: ["[Client brand]","[Competitor 1]","[Competitor 2]","[Competitor 3]","None of these"], base: "Respondents aware of at least one brand in the list.", randomize: true, analysis: "Pick-any brand×attribute association matrix: % associating each brand with each image attribute. Profile client vs. competitors; compute differentiation and image strength; feed brand-equity index. Correspondence analysis for a perceptual map.", placement: "Image block after awareness/consideration; before equity battery.", notes: "Pick-any grid is faster and less prone to halo than per-brand agreement scales for many brands. Randomize attribute rows and brand columns; keep attributes stable across waves." },
  ],
  "brand-affinity": [
    { type: "grid", stem: "How much do you agree or disagree with each of the following statements about [brand]?", attributes: ["[Brand] is a brand I love","[Brand] is a brand that fits me / suits who I am","I feel a personal connection to [brand]","I would be disappointed if [brand] were no longer available","[Brand] is a brand I feel proud to use"], scalePoints: ["Strongly agree","Agree","Neither agree nor disagree","Disagree","Strongly disagree"], base: "Respondents aware of / familiar with [brand].", randomize: true, analysis: "Per-statement % Top-2-Box; average across the battery for a Brand Affinity / Brand Love index. Track T2B vs. competitors.", placement: "Emotional/relationship block, after image and trust.", notes: "Balanced 5-pt agree scale with neutral midpoint. Randomize statement rows; watch acquiescence bias — consider one reverse-keyed item." },
  ],
  "brand-trust": [
    { type: "scale", stem: "Thinking about [brand], how much do you agree or disagree that it is 'a brand you can trust'?", scalePoints: ["Strongly agree","Agree","Somewhat agree","Neither agree nor disagree","Somewhat disagree","Disagree","Strongly disagree"], base: "Respondents aware of / familiar with [brand].", randomize: false, analysis: "% Top-2-Box on the 7-pt trust scale = brand trust; report mean and T2B vs. competitors.", placement: "Equity/relationship block, alongside image and affinity.", notes: "7-pt balanced agreement scale for finer discrimination on a key equity driver. Can be embedded as a row in the image/affinity grid if space-constrained." },
  ],
  "brand-equity-index": [
    { type: "grid", stem: "How much do you agree or disagree with each of the following statements about [brand]?", attributes: ["[Brand] meets my needs better than other brands (Meaningful)","[Brand] offers something other brands don't / stands apart (Different)","[Brand] is gaining in popularity (Different — dynamism)","[Brand] comes to mind quickly when I think of [category] (Salient)","[Brand] is a brand I would readily think of buying (Salient)"], scalePoints: ["Strongly agree","Agree","Neither agree nor disagree","Disagree","Strongly disagree"], base: "Respondents aware of [brand] (asked for client brand and key competitors).", randomize: true, analysis: "Composite equity index from the three pillars — Meaningful, Different, Salient. Compute pillar scores, combine (equal- or regression-weighted to a behavioural outcome) into a single equity index, expressed relative to the category average (=100).", placement: "Dedicated equity battery after image/affinity/trust blocks.", notes: "Operationalises the Meaningful-Different-Salient framework. Keep item wording fixed across waves; validate weights against a behavioural KPI (share/price premium); run for the competitor set to anchor the category average." },
  ],
  "brand-funnel-conversion": [
    { type: "multi", stem: "For each brand of [category], please indicate every statement that applies to you. (This single funnel grid pipes the same brand list through each stage; conversion is derived, not asked directly.)", subStems: ["I have heard of this brand (Aware)","I know this brand well (Familiar)","I would consider this brand (Consideration)","I have ever used this brand (Trial)","I have used it in the [reference period] (Current use)","It is the brand I use most often (Main brand)"], options: ["[Client brand]","[Competitor 1]","[Competitor 2]","[Competitor 3]","[Competitor 4]"], base: "All respondents (each stage based on the prior stage via routing).", randomize: true, analysis: "Derived: stage-on-stage conversion = stage ÷ prior stage (Familiarity÷Awareness, Consideration÷Familiarity, Trial÷Consideration, Current-use÷Trial, Main-brand÷Current-use) and end-to-end (Main brand ÷ Awareness). Identify the weakest 'leaky' step vs. competitors and norms.", placement: "Computed from the awareness/familiarity/consideration/trial/usage/BUMO items already in the funnel block — not a standalone question.", notes: "Funnel must be monotonic — enforce logical consistency; use prior-stage routing so each stage's base is the previous stage. Pull from existing funnel items rather than re-asking." },
  ],
  "share-of-voice": [
    { type: "multi", stem: "Which, if any, of the following brands of [category] have you seen or heard advertising for recently (in the last [reference period])?", options: ["[Client brand]","[Competitor 1]","[Competitor 2]","[Competitor 3]","[Competitor 4]","None of these"], base: "All respondents aware of at least one brand.", randomize: true, analysis: "Claimed ad awareness: % seeing advertising for each brand; share of voice = brand mentions ÷ total ad-awareness mentions. Compare claimed SOV to media-spend share to gauge cut-through.", placement: "Advertising/communications block, after the brand-equity measures.", notes: "This is perceived/claimed SOV, not media-spend SOV — label clearly. 'None of these' exclusive. Keep reference period constant across waves." },
  ],

  // ── Usage & Attitudes (U&A) ──────────────────────────────────────────────
  "category-penetration": [
    { type: "single", stem: "Which of the following best describes how often you have used or consumed [category] in the past 3 months?", scalePoints: ["I have used it in the past 3 months","I have used it, but not in the past 3 months","I have never used it"], base: "All respondents", randomize: false, analysis: "Category penetration = % selecting 'used in the past 3 months', projected to population; 'past but not recent' = lapsed pool.", placement: "Screener / early usage block, before brand-level questions.", notes: "Reference period adjusted to category cycle (P7D for daily-use, P12M for infrequent). Penetration is the base for all downstream usage metrics." },
  ],
  "usage-frequency": [
    { type: "single", stem: "In a typical month, how often do you use [category]?", scalePoints: ["Several times a day or more","About once a day","A few times a week","About once a week","2-3 times a month","About once a month","Less than once a month"], base: "Category users (used in reference period)", randomize: false, analysis: "Distribution across bands; convert midpoints to mean occasions per month for volumetric estimate and heavy/light segmentation.", placement: "Usage block, immediately after penetration screener.", notes: "Scale anchors calibrated to category cadence; midpoint conversion table defined in the analysis plan." },
  ],
  "usage-occasions": [
    { type: "multi", stem: "Thinking about all the different times you use [category], on which of the following occasions do you typically use it? Select all that apply.", options: ["First thing in the morning","With meals","As a snack or treat between meals","For an energy boost or pick-me-up","To relax or unwind","When socialising with others","While working or studying","In the evening or before bed","Other occasion"], base: "Category users", randomize: true, analysis: "Pick-any incidence per occasion; index occasions by user segment; % of occasions by type when frequency-weighted.", placement: "Usage block, after frequency.", notes: "Pick-any breadth measure; pair with a single 'most recent occasion' deep-dive if last-occasion volumetrics are required. 'Other occasion' anchored last." },
  ],
  "weight-of-usage": [
    { type: "open_numeric", stem: "On a typical day when you use [category], about how many servings do you have? Please enter a number.", base: "Category users", randomize: false, analysis: "Volume = claimed servings per occasion × occasion frequency (from usage-frequency), annualised; rank and split into terciles for heavy / medium / light (or apply category cut-offs).", placement: "Usage block, immediately after usage-frequency so the two combine into a volumetric estimate.", notes: "Quantity × frequency is the gold-standard volumetric. Cap outliers at p99; numeric entry with a sense-check range. Heavy users = top tercile of total volume." },
  ],
  "brand-repertoire": [
    { type: "multi", stem: "Which of the following brands of [category] have you used in the past 3 months? Select all that apply.", options: ["[Client brand]","[Competitor 1]","[Competitor 2]","[Competitor 3]","[Competitor 4]","[Competitor 5]","Other brand","None of these"], base: "Category users", randomize: true, analysis: "Mean repertoire size = mean count of brands selected; % solus (single-brand) users; brand-level reach within repertoire.", placement: "Brand block, after aided awareness, before share-of-wallet.", notes: "Reference period matched to penetration screener. 'None of these' and 'Other brand' anchored. Repertoire size is the denominator for share-of-wallet allocation." },
  ],
  "share-of-wallet": [
    { type: "constant_sum", stem: "Thinking about the last 10 times you purchased [category], please divide these 10 purchases across the brands you bought. Your answers should add up to 10.", options: ["[Client brand]","[Competitor 1]","[Competitor 2]","[Competitor 3]","[Competitor 4]","[Competitor 5]","Other brand"], base: "Category users with a repertoire of 1+ brands", randomize: true, analysis: "Share of wallet = points allocated to each brand / total; mean SOW per brand among users; identify dominant vs secondary brands.", placement: "Brand block, immediately after brand-repertoire.", notes: "Constant-sum to 10 (last-N framing reduces recall error vs % allocation). Pipe in only brands selected at repertoire. Sum-validation enforced." },
  ],
  "habits-practices": [
    { type: "multi", stem: "Thinking about the most recent time you used [category], which of the following did you do? Select all that apply.", options: ["Prepared it at home from scratch","Bought it ready-made or pre-prepared","Added or combined it with something else","Consumed it on its own","Consumed it on the go / away from home","Consumed it at home","Shared it with others","Had it by yourself","Followed a routine or ritual around it","Other"], base: "Category users", randomize: true, analysis: "Pick-any incidence per practice on the last occasion; cross-tab by user segment and occasion type to profile behavioural modes.", placement: "Behaviour block, after usage-occasions.", notes: "Anchored to the most-recent occasion to minimise idealised recall. Items can be structured as mutually-exclusive pairs (home/away, alone/shared). 'Other' anchored last." },
  ],
  "category-attitudes": [
    { type: "grid", stem: "How much do you agree or disagree with each of the following statements about [category]?", scalePoints: ["Strongly agree","Somewhat agree","Neither agree nor disagree","Somewhat disagree","Strongly disagree"], subStems: ["[Category] is an important part of my daily routine","I enjoy trying new types or varieties of [category]","I am willing to pay more for higher quality [category]","I worry about the health impact of [category]","I tend to stick to the brands I know and trust","Choosing [category] says something about who I am","I find the choice of [category] overwhelming","Sustainability matters to me when choosing [category]"], base: "Category users", randomize: true, analysis: "Mean and Top-2-Box agreement per statement; factor-analyse to derive attitudinal dimensions (involvement, health-consciousness, novelty-seeking); input to attitudinal segmentation.", placement: "Attitudes block, after behavioural questions.", notes: "5-pt Likert agreement battery designed for factor reduction; include reverse-coded items to detect straight-lining; randomise statement order, hold scale direction constant." },
  ],
  "needs-motivations": [
    { type: "grid", stem: "How important is each of the following to you when choosing or using [category]?", scalePoints: ["Extremely important","Very important","Moderately important","Slightly important","Not at all important"], subStems: ["It tastes good / I enjoy it","It fits my budget","It is convenient and easy","It is good for my health","It gives me energy","It helps me relax","It fits my values (ethical / sustainable)","It is a brand I can trust","It suits the occasion","It is something I can share with others"], base: "Category users", randomize: true, analysis: "Mean importance and Top-2-Box per need; derive an importance hierarchy. Recommend a MaxDiff follow-up where discrimination is needed, as flat importance ratings suffer low differentiation.", placement: "Needs block, after attitudes.", notes: "Importance battery is the pragmatic field measure; the gold standard for discrimination is MaxDiff on the same need statements when sample and length permit." },
  ],
  "path-to-purchase": [
    { type: "multi", stem: "Thinking about the last time you bought [category], which of the following did you do or use before deciding what to buy? Select all that apply.", options: ["Searched online / used a search engine","Visited the brand's or retailer's website","Read online reviews or ratings","Used social media or saw social content","Asked friends or family for recommendations","Saw an advert (TV, online, outdoor, print)","Browsed or compared products in-store","Used a price-comparison site or app","Relied on previous experience with the brand","Decided in the moment at the shelf / point of purchase","None of these"], base: "Category buyers (purchased in reference period)", randomize: true, analysis: "Pick-any incidence per touchpoint; combine with an influence follow-up to weight touchpoints by claimed impact; map trigger to source to purchase.", placement: "Purchase-journey block, after brand and channel questions.", notes: "Last-purchase reconstruction reduces telescoping. Pair with a single trigger question and an influence rating on selected touchpoints for full path mapping. 'None of these' exclusive." },
  ],
  "channel-usage": [
    { type: "constant_sum", stem: "Thinking about your last 10 purchases of [category], how many were made through each of the following channels? Your answers should add up to 10.", options: ["Large supermarket / hypermarket","Small / convenience store","Discounter","Online — retailer website or app","Online — marketplace (e.g. Amazon)","Brand's own website / direct","Specialist or independent store","Other channel"], base: "Category buyers", randomize: true, analysis: "Share of purchases by channel = points / 10; pair with a pick-any 'ever used' to separate reach from volume; identify the primary channel per buyer.", placement: "Channel block, after brand questions, before path-to-purchase.", notes: "Constant-sum gives share of volume by channel; precede with a pick-any channel-reach question if breadth is also required. 'Other channel' anchored last." },
  ],
  "media-consumption": [
    { type: "grid", stem: "How often do you personally use each of the following types of media or platforms?", scalePoints: ["Several times a day","About once a day","A few times a week","About once a week","Less often","Never"], subStems: ["Live / broadcast TV","Streaming video (e.g. Netflix, YouTube)","Radio or music streaming (e.g. Spotify)","Online news or websites","Print newspapers or magazines","Facebook","Instagram","TikTok","X (Twitter)","Podcasts","Email newsletters","Out-of-home (billboards, transit, posters)"], base: "All respondents", randomize: true, analysis: "Reach = % using each channel at all (net of 'Never'); frequency = mean exposures from scale midpoints; combine into reach × frequency for media planning and channel prioritisation by segment.", placement: "Media block, late in survey (non-category-specific).", notes: "Reach × frequency grid for media planning; hold a small set of anchor channels non-randomised if trend-tracking. Update the platform list per market/wave." },
  ],
  "lapsing-churn-reasons": [
    { type: "multi", stem: "You mentioned you have used [category] in the past but not recently. Which of the following are reasons you stopped or cut back? Select all that apply.", options: ["It became too expensive","I found a better alternative","My tastes or preferences changed","Health or dietary reasons","It was no longer convenient to buy","Quality got worse","I simply lost interest / got bored","Changes in my lifestyle or circumstances","I had a bad experience","No particular reason","Other reason (please specify)"], base: "Lapsed users (used previously but not in the reference period).", randomize: true, analysis: "Pick-any incidence per reason; rank churn drivers; cross-tab against former brand and weight-of-usage to find which segments are most at-risk and why.", placement: "Lapsing block, routed from the penetration screener for lapsed users only.", notes: "Pre-coded reasons plus an open 'Other reason'; pair with a verbatim open-end for richer churn narratives. 'No particular reason' and 'Other' anchored last." },
  ],

  // ── Purchase Behaviour & Pricing ─────────────────────────────────────────
  "purchase-triggers": [
    { type: "multi", stem: "Which of the following, if any, would make you more likely to choose [product] over the alternatives you currently consider? Select all that apply.", options: ["It fits easily into my daily routine","The taste/flavor appeals to me","It's better value for the money than alternatives","It comes from a brand I trust","It's made with ingredients I feel good about","It's recommended by people I know","It's recommended by an expert or professional","It's convenient to buy where I already shop","It has the right pack size/format for me","The packaging is appealing or practical","It's better for the environment","None of these"], base: "All respondents", randomize: true, analysis: "% selecting each trigger (pick-any); rank by incidence. Validate with a follow-up MaxDiff to derive importance and separate true drivers from table-stakes.", placement: "After concept exposure; before barriers and pricing.", notes: "Anchor 'None of these' exclusive and fixed at the bottom. Keep the list MECE; pre-test wording per category." },
  ],
  "purchase-barriers": [
    { type: "multi", stem: "You said you probably or definitely would not buy [product]. Which of the following, if any, are reasons why? Select all that apply.", options: ["It's too expensive for what it offers","I'm happy with what I currently use","I don't see how it's different or better","I don't trust the brand","I have concerns about the ingredients/contents","I'm not sure how or when I'd use it","The taste/flavor doesn't appeal to me","It's not available where I usually shop","The pack size/format doesn't suit me","I've had a bad experience with something similar","Some other reason (please specify)","No particular reason"], base: "Rejectors: respondents answering 'Probably/Definitely would not buy' on purchase intention.", randomize: true, analysis: "% citing each barrier among rejectors; rank to prioritize. Net-code the open 'Some other reason' verbatims back into the frame.", placement: "Immediately after purchase-intention, routed to rejectors only.", notes: "Pre-coded battery plus open-end capture. Anchor the open-other and 'No particular reason' at the bottom; 'No particular reason' exclusive." },
  ],
  "trial-intent": [
    { type: "scale", stem: "If [product] were available where you normally shop, how likely would you be to try it?", scalePoints: ["Definitely would try","Probably would try","Might or might not try","Probably would not try","Definitely would not try"], base: "All respondents", randomize: false, analysis: "% Top-2-Box benchmarked against launch/trial norms; report % 'Definitely would try' separately as the strongest signal.", placement: "After concept exposure; with or just before purchase intention.", notes: "Five-point balanced likelihood scale; keep order fixed. Distinguish trial (first purchase) from repeat." },
  ],
  "repeat-purchase-intent": [
    { type: "scale", stem: "Now that you've used [product], how likely would you be to buy it again?", scalePoints: ["Definitely would buy again","Probably would buy again","Might or might not buy again","Probably would not buy again","Definitely would not buy again"], base: "Respondents who have tried/used the product (post-trial or in-market triers).", randomize: false, analysis: "% Top-2-Box as the repeat signal; report % 'Definitely' separately. Pair with trial intent to model trial-to-repeat conversion.", placement: "Post-trial wave, or after usage in an in-home-use test (HUT).", notes: "Mirror the trial-intent scale wording for comparability. Base must be triers only." },
  ],
  "willingness-to-pay": [
    { type: "open_numeric", stem: "Thinking about everything [product] offers, what is the most you would be willing to pay for it before you'd decide it isn't worth it?", base: "All respondents (or category buyers)", analysis: "Distribution of stated max price: median and mean WTP, percentiles, and demand at candidate price points. Cross-check against Gabor–Granger or van Westendorp where fielded.", placement: "Pricing block, after the concept is fully understood; before any price is shown.", notes: "Open numeric with currency mask and sensible min/max validation; specify unit/pack size in the stem. Direct WTP can overstate; triangulate with an indirect technique when stakes are high." },
  ],
  "gabor-granger": [
    { type: "scale", stem: "At a price of [PRICE], how likely would you be to buy [product]?", scalePoints: ["Definitely would buy","Probably would buy","Might or might not buy","Probably would not buy","Definitely would not buy"], base: "All respondents (or category buyers)", randomize: true, analysis: "Repeat the item across a randomized price ladder (one price per screen). At each price, % Top-2-Box (or 'Definitely') = estimated demand; plot demand and price×demand revenue curves to find the revenue-maximizing price and derive elasticity between steps.", placement: "Pricing block, late, after the concept is understood; one price point per screen.", notes: "Randomize starting price and present points monotonically per respondent to limit anchoring; ladder typically 4–6 points. Once rejected at a price, higher prices can be inferred as rejected. Distinct from van Westendorp (price perception) — this measures demand at specific prices." },
  ],
  "value-for-money": [
    { type: "scale", stem: "Thinking about its price and what it delivers, how would you rate [product] as value for money?", scalePoints: ["Excellent value","Good value","Fair value","Poor value","Very poor value"], base: "All respondents (or those who have evaluated/used the product).", randomize: false, analysis: "% Top-2-Box ('Excellent' + 'Good value'); track against category benchmarks and the competitive set. Cross-tab by price tier and segment.", placement: "After concept/price exposure or post-usage; within the evaluation block.", notes: "Five-point unipolar value scale, fixed order from best to worst. Keep distinct from overall satisfaction and from absolute price perception." },
  ],
  "promo-responsiveness": [
    { type: "scale", stem: "How well does each of the following statements describe you when shopping for [category]?", scalePoints: ["Describes me completely","Describes me well","Describes me somewhat","Describes me slightly","Does not describe me at all"], subStems: ["I often switch brands to take advantage of a special offer or coupon","I tend to stock up on a product when it's on promotion","I check for discounts or deals before buying in this category","I'm willing to try a new brand if it's on a special introductory offer","I would buy a larger pack if it lowered the price per unit","The regular (non-promoted) price is what matters most to me, not deals"], base: "All respondents (or category buyers)", randomize: true, analysis: "Mean and % Top-2-Box per statement to score deal proneness; build a composite deal-proneness index (reverse-scoring the final price-focused item) and segment into deal-seekers vs. full-price buyers.", placement: "Attitudinal block, after pricing items; can precede segmentation questions.", notes: "Agreement-style battery (randomize statement order, keep scale fixed). The last item is reverse-keyed as a validity check." },
  ],

  // ── Concept & Product Testing ────────────────────────────────────────────
  "overall-liking": [
    { type: "scale", stem: "Overall, how much do you like or dislike [product]?", scalePoints: ["Like extremely","Like very much","Like moderately","Like slightly","Neither like nor dislike","Dislike slightly","Dislike moderately","Dislike very much","Dislike extremely"], base: "All exposed to the concept/product", randomize: false, analysis: "Mean hedonic score (1–9) + % Top-2-Box (Like very much/extremely). For concept-only tests, substitute a 5-pt overall-opinion scale (Excellent/Very good/Good/Fair/Poor) and report % T2B.", placement: "First evaluative item after exposure, before diagnostic/likes-dislikes items.", notes: "9-pt hedonic is the sensory gold standard (Peryam & Pilgrim); present anchors top-to-bottom. Do not randomize an ordered scale." },
  ],
  "likes-dislikes": [
    { type: "open_text", stem: "What, if anything, do you LIKE about [product]? Please tell us everything that comes to mind.", base: "All exposed to the concept/product", randomize: false, analysis: "Code verbatims into a likes theme net; report % mentioning each theme. Pair with the dislikes item for a likes-vs-dislikes balance read.", placement: "Immediately after overall liking, before specific diagnostics so reactions are unaided.", notes: "Field as a two-part open: ask LIKES first, then a separate matched DISLIKES open. Keep unaided; do not provide a code list to respondents." },
  ],
  uniqueness: [
    { type: "scale", stem: "How new and different is [product] compared with other products available to you?", scalePoints: ["Extremely new and different","Very new and different","Somewhat new and different","Slightly new and different","Not at all new and different"], base: "All exposed to the concept", randomize: false, analysis: "% Top-2-Box (Extremely/Very new and different). High uniqueness + high purchase intent flags genuine innovation; high uniqueness + low PI flags niche or confusing.", placement: "Within concept diagnostics, after overall opinion/PI.", notes: "Classic BASES 'new and different' distinctiveness item; ordered scale, do not randomize." },
  ],
  relevance: [
    { type: "scale", stem: "[Product] solves a problem or meets a need that is important to me.", scalePoints: ["Agree completely","Agree somewhat","Neither agree nor disagree","Disagree somewhat","Disagree completely"], base: "All exposed to the concept", randomize: false, analysis: "% Top-2-Box (Agree completely/somewhat) as the relevance/need-fit read. Cross with purchase intent; relevance is a primary driver of trial in concept-screening models.", placement: "Within concept diagnostics, alongside uniqueness and believability.", notes: "5-pt agreement framed on personal need-fit; ordered scale, do not randomize. Keep 'me/my' framing to capture personal relevance, not category relevance." },
  ],
  believability: [
    { type: "scale", stem: "How believable are the claims made about [product]?", scalePoints: ["Extremely believable","Very believable","Somewhat believable","Slightly believable","Not at all believable"], base: "All exposed to the concept", randomize: false, analysis: "% Top-2-Box (Extremely/Very believable) as the credibility read. Low believability alongside high appeal flags a claim-support/reason-to-believe gap.", placement: "Within concept diagnostics, after the benefit/claim has been read.", notes: "5-pt believability; ordered scale, do not randomize. If the concept makes a single hero claim, anchor the stem to that claim." },
  ],
  comprehension: [
    { type: "scale", stem: "How easy or difficult is it to understand what [product] is and what it offers?", scalePoints: ["Very easy to understand","Somewhat easy to understand","Neither easy nor difficult","Somewhat difficult to understand","Very difficult to understand"], base: "All exposed to the concept", randomize: false, analysis: "% Top-2-Box (Very/Somewhat easy) for the clarity read. Pair with an open playback: code whether the main message is played back correctly; report % correct playback and common misinterpretations.", placement: "Early in diagnostics, right after exposure, before persuasion items that could contaminate recall.", notes: "Field as a two-part item: (1) this ease-of-understanding scale, then (2) an open playback — 'In your own words, what is the main message [product] is trying to communicate?' Keep playback unaided." },
  ],
  "paired-preference": [
    { type: "single", stem: "Having tried both products, which one do you prefer overall?", options: ["Prefer Product A","Prefer Product B","No preference"], base: "Respondents who blind-tested both products (paired/sequential monadic with rotation).", randomize: true, analysis: "% preferring each product; test the split against 50/50 (binomial/sign test) excluding or allocating no-preference per convention. Report net preference and significance.", placement: "After both products have been tried and individually rated.", notes: "Blind (unbranded) test; rotate order of A/B to control order effects. Always offer an explicit 'No preference'. Labels A/B map to rotated samples, not fixed products." },
  ],
  "expected-frequency": [
    { type: "scale", stem: "If [product] were available, how often would you buy it?", scalePoints: ["More than once a week","About once a week","2–3 times a month","About once a month","Once every 2–3 months","Less often than once every 2–3 months","Never"], base: "All exposed to the concept (often asked among those positive on purchase intent).", randomize: false, analysis: "Convert to an annualized claimed-frequency estimate (mean purchases/year); deflate claimed frequency in volumetric forecasting models (claimed overstates actual).", placement: "After purchase intent, within the demand/volumetric battery.", notes: "Ordered frequency scale, do not randomize. Anchor exact frequencies for annualization. Treat as claimed — always deflate via category norms before forecasting." },
  ],
  "price-perception-concept": [
    { type: "scale", stem: "At the price shown, [product] is…", scalePoints: ["An excellent value for the money","A good value for the money","A fair value for the money","A poor value for the money","A very poor value for the money"], base: "Priced concept: all exposed to the concept WITH a price shown.", randomize: false, analysis: "% Top-2-Box (Excellent/Good value) as the value-for-money read; cross with purchase intent at the tested price. UNPRICED variant: replace with an open-numeric expected-price item and compare expected vs intended/actual price.", placement: "After purchase intent; in priced cells immediately following price exposure.", notes: "Two modes. PRICED: this 5-pt value scale. UNPRICED: open-numeric expected-price capture benchmarked against intended price. Do not show the price-value scale in an unpriced cell." },
  ],

  // ── Customer Experience & Satisfaction ───────────────────────────────────
  csat: [
    { type: "scale", stem: "Overall, how satisfied or dissatisfied are you with [product/service/interaction]?", scalePoints: ["Very dissatisfied","Dissatisfied","Neither satisfied nor dissatisfied","Satisfied","Very satisfied"], base: "All customers / users with relevant experience", analysis: "CSAT = % Top-2-Box (Satisfied + Very satisfied); report mean (1–5) as secondary. Relational: overall relationship; transactional: specific touchpoint.", placement: "Relational CSAT early in survey; transactional immediately after the touchpoint.", notes: "Balanced 5-point scale with labeled points; keep polarity consistent. Avoid mixing with 7- or 10-point CSAT in trackers." },
  ],
  ces: [
    { type: "scale", stem: "To what extent do you agree or disagree with the following statement: '[Company] made it easy for me to handle my issue.'", scalePoints: ["1 — Strongly disagree","2","3","4","5","6","7 — Strongly agree"], base: "Customers who recently completed a service interaction or resolved an issue", analysis: "CES = % Agree (Top-3-Box: 5–7); report mean as secondary. Track against churn and remediation cost.", placement: "Immediately after the issue-resolution or service touchpoint (transactional only).", notes: "CES 2.0 ease-of-handling statement on a 7-point agreement scale; anchor only the endpoints." },
  ],
  "repurchase-intention": [
    { type: "scale", stem: "How likely are you to continue using [brand] / purchase from [brand] again [next renewal / in the future]?", scalePoints: ["Very unlikely","Unlikely","Neither likely nor unlikely","Likely","Very likely"], base: "All current customers / active subscribers", analysis: "Repurchase intention = % Top-2-Box (Likely + Very likely); report mean (1–5) as secondary. Validate against actual renewal/repurchase behavior.", placement: "Relational placement, mid-to-late in survey alongside loyalty and value items.", notes: "Balanced 5-point likelihood scale; phrase for renewal in subscription contexts, repurchase in transactional contexts." },
  ],
  "complaint-incidence": [
    { type: "single", stem: "In the past [6 months], did you experience any problem or issue with [brand]'s products or services?", options: ["Yes","No"], base: "All customers / users", analysis: "Problem incidence = % Yes. Gateway to the complaint-resolution funnel; track incidence over time and by segment.", placement: "Begins the problem-resolution module; relational or transactional.", notes: "First step of the funnel; subsequent items are piped to those answering 'Yes'." },
    { type: "grid", stem: "Thinking about that problem, please answer the following:", subStems: ["Did you report or complain about the problem to [brand]?","Was the problem resolved to your satisfaction?"], scalePoints: ["Yes","No"], base: "Customers who experienced a problem (piped from 'Yes').", analysis: "Complained % and resolved-satisfactorily % among those with a problem; resolution rate = % resolved of those who complained.", placement: "Immediately after the problem-incidence question, piped to problem-havers.", notes: "Yes/No grid for funnel steps; follow with a satisfaction-with-handling rating for those who complained." },
    { type: "scale", stem: "How satisfied or dissatisfied were you with the way [brand] handled your problem?", scalePoints: ["Very dissatisfied","Dissatisfied","Neither satisfied nor dissatisfied","Satisfied","Very satisfied"], base: "Customers who complained / reported the problem", analysis: "Handling satisfaction = % Top-2-Box; compare against overall CSAT to quantify the service-recovery gap (recovery paradox).", placement: "After the complaint/resolution funnel, piped to those who complained.", notes: "Mirrors the 5-point CSAT scale for comparability." },
  ],
  "key-driver-importance": [
    { type: "grid", stem: "Please rate [brand]'s performance on each of the following:", scalePoints: ["1 — Poor","2","3","4","5","6","7","8","9","10 — Excellent"], attributes: ["Product/service quality","Ease of doing business","Value for money","Responsiveness / speed","Staff knowledge and helpfulness","Reliability / consistency","Problem resolution","Communication and transparency"], base: "All customers / users with relevant experience", randomize: true, analysis: "Derived (stated-less) importance: regress/Shapley each attribute's performance against an overall outcome (CSAT/NPS); plot derived importance (X) vs performance (Y) in a quadrant map to prioritize 'high importance / low performance' attributes.", placement: "Core driver battery, mid-survey, after the outcome metric it is regressed against.", notes: "Derived importance avoids stated-importance ceiling effects. Randomize attribute order; keep the same outcome metric for all attributes; 8–12 attributes is typical." },
  ],

  // ── Advertising & Communications ─────────────────────────────────────────
  "ad-recall": [
    { type: "open_text", stem: "Thinking about advertising you may have seen, heard, or read recently, what advertising for [category] do you recall? Please describe anything that comes to mind — the brand, what happened, what it was about.", base: "All respondents", randomize: false, analysis: "Verbatims coded to brand/campaign; % with any unaided recall and % recalling [Client brand] specifically. An aided follow-up reads % recalling once cued.", placement: "Very first item, before any brand or creative is shown.", notes: "Pure unaided playback; capture before exposure. Probe once ('What else?'). Aided version follows as a separate cued item." },
  ],
  "ad-recognition": [
    { type: "single", stem: "Have you seen, heard, or read this advertising before — in any form, anywhere?", scalePoints: ["Yes, definitely","Yes, I think so","No, I don't think so","No, definitely not"], base: "All respondents (shown the de-branded creative).", randomize: false, analysis: "% recognizing = Top-2-Box ('definitely' + 'think so'). Defines the recognizer base for brand linkage.", placement: "Immediately after first exposure to the de-branded creative.", notes: "Strip all brand identifiers from the stimulus to avoid cueing. Single-exposure, natural viewing. Routes recognizers into brand-linkage." },
  ],
  "brand-linkage": [
    { type: "open_text", stem: "Which brand do you think this advertising was for?", base: "Recognizers only (Top-2-Box at ad-recognition).", randomize: false, analysis: "Open verbatim coded as correct ([Client brand]) / wrong brand / don't know. % correct attribution = brand linkage. Report 'misattributed to competitor' separately.", placement: "Directly after ad-recognition, still on de-branded creative, before any branded reveal.", notes: "Keep open-ended to avoid handing respondents the answer; a closed brand-list version risks inflating linkage. Asked only of recognizers." },
  ],
  "message-takeout": [
    { type: "open_text", stem: "In your own words, what do you think was the main point or message this advertising was trying to get across?", base: "All respondents exposed to the creative", randomize: false, analysis: "Verbatims coded against the intended message map; % correct takeout (primary intended message), % partial, % miscomprehension/off-message. Report secondary messages.", placement: "After recognition/linkage, before evaluative scales so reactions don't contaminate playback.", notes: "Unaided and open to capture true communication. Probe once ('Anything else it was trying to tell you?'). Code blind to condition." },
  ],
  persuasion: [
    { type: "scale", stem: "Which one of these brands of [category] would you choose next time you buy?", scalePoints: ["Definitely [Client brand]","Probably [Client brand]","Might or might not choose [Client brand]","Probably another brand","Definitely another brand"], options: ["[Client brand]","[Competitor 1]","[Competitor 2]","[Competitor 3]","No preference"], base: "All (asked identically pre- and post-exposure, or exposed cell vs matched control).", randomize: true, analysis: "Persuasion = percentage-point shift in brand choice / intent toward [Client brand], post minus pre (or exposed minus control). Report T2B intent lift with significance test.", placement: "Brand-choice asked pre-exposure (early) and again post-exposure; or the control cell sees no ad.", notes: "Identical wording both waves to isolate the ad-driven shift. Randomize brand list (anchor 'No preference'). Monadic exposed-vs-control avoids pre-sensitization." },
  ],
  "ad-likeability": [
    { type: "scale", stem: "Overall, how much did you like or dislike this advertising?", scalePoints: ["Liked it a lot","Liked it somewhat","Neither liked nor disliked it","Disliked it somewhat","Disliked it a lot"], base: "All respondents exposed to the creative", randomize: false, analysis: "% Top-2-Box ('Liked a lot' + 'Liked somewhat') benchmarked against category copy-test norms (e.g. Kantar/Ipsos Link, ARS).", placement: "Evaluation block, after open-ended message takeout.", notes: "Standard 5-pt overall liking. Keep before diagnostic likes/dislikes so the global rating is unbiased." },
  ],
  "ad-distinctiveness": [
    { type: "grid", stem: "How much do you agree or disagree that each of the following describes this advertising?", scalePoints: ["Strongly agree","Somewhat agree","Neither agree nor disagree","Somewhat disagree","Strongly disagree"], subStems: ["It is different from other advertising for [category]","It stood out and grabbed my attention","It is unique / unlike other ads I've seen","It held my interest the whole way through","It is the kind of ad people would talk about"], base: "All respondents exposed to the creative", randomize: true, analysis: "% Top-2-Box ('Strongly' + 'Somewhat agree') per statement; distinctiveness and engagement indices reported vs norms.", placement: "Diagnostic block, after overall liking.", notes: "Randomize statement order. Balanced 5-pt agree/disagree to limit acquiescence. Distinctiveness and engagement items can be summarized as separate indices." },
  ],
  "call-to-action": [
    { type: "multi", stem: "After seeing this advertising, which of the following, if any, would you be likely to do? Select all that apply.", options: ["Look for more information about [Client brand]","Visit the [Client brand] website or app","Search for [Client brand] online","Visit a store to look at the product","Buy or order the product","Recommend or talk about it to someone else","Follow or engage with the brand on social media","None of these"], base: "All respondents exposed to the creative", randomize: true, analysis: "% selecting each action (pick-any); report any-action incidence and key conversion-oriented actions (visit/buy/search) separately.", placement: "End of evaluation block, after persuasion/intent.", notes: "'None of these' exclusive and anchored last; randomize action list. Multi-response, so percentages sum to >100%." },
  ],

  // ── UX Research ──────────────────────────────────────────────────────────
  "task-success": [
    { type: "single", stem: "Were you able to complete that task successfully?", options: ["Yes, completely","Partially","No"], base: "Participants attempting the task.", randomize: false, analysis: "Self-reported completion as a companion to observed success; report % success with a 95% binomial (adjusted-Wald) confidence interval.", placement: "Post-task, immediately after the task attempt.", notes: "PRIMARY metric is observed binary/leveled task success scored by the moderator (or via success criteria in an unmoderated test), NOT this self-report item — claimed success routinely diverges from observed." },
  ],
  "time-on-task": [
    { type: "open_numeric", stem: "Roughly how long do you feel that task took you to complete?", base: "Participants who completed the task.", randomize: false, analysis: "Self-reported duration is a perceptual companion only; report observed time on task using the geometric mean (and geometric SD) over successful tasks.", placement: "Post-task, immediately after completion.", notes: "PRIMARY metric is timer-based time on task captured during the test, NOT this self-report — analyze completed tasks only and summarize with the geometric mean to reduce right-skew." },
  ],
  "error-rate": [
    { type: "single", stem: "While completing that task, did you make any mistakes or slips (for example, a wrong click, wrong entry, or a step you had to redo)?", options: ["No mistakes","One mistake","A few mistakes","Many mistakes"], base: "Participants attempting the task.", randomize: false, analysis: "Self-report companion only; report the primary error rate as errors per task relative to defined error opportunities (mean errors/task and % of tasks error-free).", placement: "Post-task, immediately after the task attempt.", notes: "PRIMARY metric is moderator-observed errors counted against pre-defined error opportunities, NOT this self-report — participants under-report slips they did not notice." },
  ],
  sus: [
    { type: "scale", stem: "Please respond to each statement by indicating how much you agree or disagree, based on your experience using [product].", scalePoints: ["Strongly disagree","Disagree","Neither agree nor disagree","Agree","Strongly agree"], attributes: ["I think that I would like to use this system frequently.","I found the system unnecessarily complex.","I thought the system was easy to use.","I think that I would need the support of a technical person to be able to use this system.","I found the various functions in this system were well integrated.","I thought there was too much inconsistency in this system.","I would imagine that most people would learn to use this system very quickly.","I found the system very cumbersome to use.","I felt very confident using the system.","I needed to learn a lot of things before I could get going with this system."], base: "All participants, after completing core tasks.", randomize: false, analysis: "Score 0–100: for odd (positive) items contribution = (response − 1); for even (negative) items contribution = (5 − response); sum and multiply by 2.5. Benchmark mean ≈68; report mean with CI and percentile/grade.", placement: "Post-test (study-level), after all tasks are complete.", notes: "Standardized 10-item instrument with strictly alternating positive/negative wording — keep item order fixed and do NOT randomize; 5-point agreement scale only." },
  ],
  seq: [
    { type: "scale", stem: "Overall, how difficult or easy was that task to complete?", scalePoints: ["Very difficult","2","3","4","5","6","Very easy"], base: "Participants who attempted the task.", randomize: false, analysis: "Report the mean (and median) per task; benchmark mean ≈5.5. Flag tasks scoring below benchmark and correlate with observed success/time.", placement: "Post-task, immediately after each task (before any debrief).", notes: "Single 7-point ease item with only the endpoints labeled; ask the identical question after every task for comparability." },
  ],
  "umux-lite": [
    { type: "scale", stem: "Please indicate how much you agree or disagree with each statement, based on your experience using [product].", scalePoints: ["Strongly disagree","Disagree","Neither agree nor disagree","Agree","Strongly agree"], attributes: ["[Product]'s capabilities meet my requirements.","[Product] is easy to use."], base: "All participants, post-test.", randomize: false, analysis: "Mean of the two items rescaled 0–100 [(mean − 1)/4 × 100]; optionally apply the published regression to estimate SUS-equivalent scores. Report mean with CI.", placement: "Post-test (study-level), alongside or in place of SUS.", notes: "Two positively worded items (capability + ease); a matching 7-point agreement scale is also valid — keep the scale consistent across waves." },
  ],
  "first-click": [
    { type: "open_text", stem: "On the screen you just saw, where would you click first to begin [task goal]? Briefly describe the spot you chose and why.", base: "Participants shown the stimulus screen.", randomize: false, analysis: "Self-report rationale is a companion for interpreting intent; report the primary metric as % of participants whose first click lands in a pre-defined correct target zone (with CI), plus a first-click heatmap.", placement: "Immediately after exposing the stimulus, before any further interaction.", notes: "PRIMARY metric is the recorded first-click location in a first-click test, NOT this self-report — first-click success strongly predicts overall task success." },
  ],
  findability: [
    { type: "single", stem: "In the menu structure you just navigated, where would you expect to find [item]? Select the location you would choose.", options: ["[Category A]","[Category B]","[Category C]","[Category D]","I'm not sure"], base: "Participants completing the tree-test task.", randomize: true, analysis: "Companion self-report only; report tree-testing metrics: % success, % directness (no backtracking), and median time per item, with a first-click/path analysis.", placement: "During an unmoderated tree test, one screen per target item.", notes: "PRIMARY metric is tree-testing behaviour (success, directness, path, time) on a text-only navigation tree, NOT this self-report — randomize top-level option order to control position bias." },
  ],
  learnability: [
    { type: "scale", stem: "Thinking about this most recent attempt compared with your earlier attempts, how easy was it to complete the task this time?", scalePoints: ["Much harder","2","3","4","5","6","Much easier"], base: "Participants on each repeated trial (trials 2+).", randomize: false, analysis: "Self-report companion to track perceived improvement; report the primary learnability metric as the slope of time-on-task (and errors) across repeated trials — flatter/declining curves indicate faster learning.", placement: "Post-trial, after each repeated attempt of the same task.", notes: "PRIMARY metric is the trial-over-trial change in time/errors from a repeated-trial test (same participants, same task, multiple trials), NOT this self-report." },
  ],
  "nasa-tlx": [
    { type: "scale", stem: "Rate your experience of the task on each of the following dimensions.", scalePoints: ["0 (Very low)","10","20","30","40","50","60","70","80","90","100 (Very high)"], attributes: ["Mental demand — How mentally demanding was the task?","Physical demand — How physically demanding was the task?","Temporal demand — How hurried or rushed was the pace of the task?","Performance — How successful were you in accomplishing what you were asked to do? (Perfect → Failure)","Effort — How hard did you have to work to accomplish your level of performance?","Frustration — How insecure, discouraged, irritated, stressed, and annoyed were you?"], base: "Participants who attempted the task.", randomize: false, analysis: "Raw TLX: average the six 0–100 subscale ratings (unweighted) for an overall workload score; also report subscales individually. Note the Performance anchor runs Good→Bad.", placement: "Post-task, immediately after the task.", notes: "21-point scales (0–100 in steps of 5) per the original instrument; Raw TLX omits the pairwise weighting step. Keep the Performance item's reversed anchors." },
  ],
  desirability: [
    { type: "multi", stem: "Which of these words best describe your experience of using [product]? Please select the 5 words that fit best.", options: ["Accessible","Advanced","Annoying","Appealing","Approachable","Boring","Busy","Clean","Cluttered","Complex","Confusing","Consistent","Cutting edge","Dated","Difficult","Easy to use","Efficient","Familiar","Fast","Frustrating","Fun","Hard to use","Helpful","High quality","Inconsistent","Innovative","Intimidating","Inviting","Old","Organized","Overwhelming","Plain","Powerful","Predictable","Professional","Reliable","Rigid","Simplistic","Slow","Stressful","Time-consuming","Trustworthy","Unconventional","Understandable","Unrefined","Usable","Useful"], base: "All participants, post-test.", randomize: true, analysis: "Frequency count of selected cards; compute the ratio of positive to negative selections and review the top cards qualitatively (optional follow-up 'why did you choose…').", placement: "Post-test (study-level), after task completion.", notes: "Microsoft Product Reaction Cards method (full set is 118 cards, ~60% positive/40% negative); here a balanced subset is shown — restrict selection to 3–5 cards and randomize card order." },
  ],
  "feature-adoption": [
    { type: "single", stem: "Before today, how often had you used [feature] in [product]?", options: ["I didn't know this feature existed","I knew about it but never used it","I've used it once or twice","I use it occasionally","I use it regularly"], base: "All users / triers of the product.", randomize: false, analysis: "Self-report companion measuring claimed awareness vs usage; report the primary adoption metric from analytics as % of active users who use the feature × usage frequency × subsequent retention.", placement: "In-product survey or post-test questionnaire.", notes: "PRIMARY metric is product analytics (feature reach, frequency, and retained usage), NOT this self-report — claimed usage tends to overstate measured usage." },
  ],
  engagement: [
    { type: "single", stem: "Over the past 30 days, how often did you use [product]?", options: ["Every day or almost every day","Several times a week","About once a week","A few times this month","Once this month","Not at all"], base: "Users active in the past 30 days.", randomize: false, analysis: "Self-report frequency companion; report the primary engagement metrics from analytics: DAU/MAU stickiness ratio and sessions per user over the period.", placement: "In-product or panel survey.", notes: "PRIMARY metric is product analytics (DAU/MAU ratio, session frequency), NOT this self-report — use this item only to segment or triangulate behavioural data." },
  ],
  "retention-churn": [
    { type: "scale", stem: "How likely are you to still be using [product] three months from now?", scalePoints: ["Definitely will not be using it","2","3","4","5","6","Definitely will be using it"], base: "Current users of the product.", randomize: false, analysis: "Self-report intention-to-continue companion; report the primary retention metrics from analytics: cohort retention curves (D1/D7/D30) and churn % per cohort.", placement: "In-product or lifecycle survey.", notes: "PRIMARY metric is cohort-based retention/churn from product analytics, NOT this self-report — stated intention-to-continue is a leading indicator only and tends to overstate actual retention." },
  ],
  "heart-framework": [
    { type: "scale", stem: "Overall, how satisfied are you with your experience using [product]?", scalePoints: ["Very dissatisfied","Dissatisfied","Somewhat dissatisfied","Neither satisfied nor dissatisfied","Somewhat satisfied","Satisfied","Very satisfied"], base: "All users / participants.", randomize: false, analysis: "This Happiness self-report (satisfaction; pair with task-level SEQ and a likelihood-to-recommend item) supplies the survey side of HEART; report % T2B satisfaction with CI and trend over time.", placement: "In-product or post-test happiness survey.", notes: "HEART is a Goals-Signals-Metrics framework spanning Happiness, Engagement, Adoption, Retention, and Task-success — Happiness is typically self-report (this item); the others are primarily behavioural analytics." },
  ],

  // ── Banking & Payments ───────────────────────────────────────────────────
  "main-bank-share": [
    { type: "single", stem: "Which one bank do you consider your main bank — that is, the one you use most often and where your main income or salary is paid?", options: ["[Client]","[Competitor A]","[Competitor B]","[Competitor C]","Another bank (please specify)","I don't have a main bank"], base: "All respondents.", randomize: true, analysis: "% naming each brand (main-bank share); track [Client] vs competitors. Salary-domiciliation proxy.", placement: "Relationship block, early.", notes: "Single-mention forced. 'Another bank' and 'no main bank' anchored last, exclusive, not randomized." },
  ],
  "bank-switching-intent": [
    { type: "scale", stem: "How likely are you to switch your main bank to a different bank in the next 12 months?", scalePoints: ["Definitely will switch","Probably will switch","Might or might not switch","Probably will not switch","Definitely will not switch"], base: "All respondents with a main bank.", randomize: false, analysis: "% Top-2-Box (definitely/probably will switch) = active switching intent.", placement: "Relationship block, after main-bank identification.", notes: "Routes T3B to switching-triggers; bottom-box to barriers/inertia." },
  ],
  "switching-triggers-barriers": [
    { type: "multi", stem: "You said you might switch your main bank. Which of the following would be reasons for you to switch?", options: ["High or unexpected fees and charges","Poor customer service","Better rates or rewards elsewhere","Poor mobile app or online banking","Problems resolving an issue or complaint","Branch closed or hard to reach","A life change (moving, new job, marriage)","An attractive switching offer or bonus","Concerns about security or fraud","Other (please specify)"], base: "Potential switchers (switching-intent T3B: definitely/probably/might switch).", randomize: true, analysis: "% citing each trigger among potential switchers; rank drivers.", placement: "Relationship block, routed from switching-intent.", notes: "Pre-coded + open 'Other'. Paired with the barrier battery below." },
    { type: "multi", stem: "What stops you from switching your main bank, even if you have considered it?", options: ["Too much hassle to move payments and direct debits","Loyalty or long relationship with my bank","All my products are in one place","No bank is clearly better","Worried something will go wrong in the move","Locked in by a mortgage, loan, or product","I simply haven't gotten around to it","Nothing stops me — I'm happy with my bank","Other (please specify)"], base: "Stayers (switching-intent bottom-2-box) and 'might or might not' switchers.", randomize: true, analysis: "% citing each barrier/inertia factor among stayers; identify dominant lock-ins.", placement: "Relationship block, routed from switching-intent.", notes: "Pre-coded + open 'Other'. 'Nothing stops me' exclusive, anchored." },
  ],
  "cross-sell-intent": [
    { type: "single", stem: "If you were to take out [PRODUCT] in the future, which bank would you go to first?", options: ["My current main bank","[Competitor A]","[Competitor B]","A fintech or neobank","A price-comparison site or broker","I don't know"], base: "All respondents (optionally those open to [PRODUCT]).", randomize: true, analysis: "% choosing current main bank vs competitors/third parties = deepening/cross-sell potential.", placement: "Product block, per relevant product.", notes: "Single-mention. 'I don't know' anchored, exclusive. Pipe [PRODUCT] per category of interest." },
  ],
  "consolidation-intent": [
    { type: "scale", stem: "How likely are you to bring more of your financial products together with a single bank over the next 12 months?", scalePoints: ["Definitely will consolidate","Probably will consolidate","Might or might not","Probably will not","Definitely will not"], base: "Respondents holding products at more than one provider.", randomize: false, analysis: "% Top-2-Box consolidation intent.", placement: "Relationship block.", notes: "T3B routes to the follow-up 'winning bank' item below." },
    { type: "single", stem: "If you brought your financial products together with one bank, which bank would win most of your business?", options: ["[Client]","[Competitor A]","[Competitor B]","[Competitor C]","A fintech or neobank","Another bank (please specify)","Not sure"], base: "Consolidation-intent T3B (definitely/probably/might consolidate).", randomize: true, analysis: "% naming each brand as the consolidation winner; share-of-wallet capture potential.", placement: "Relationship block, routed from consolidation-intent.", notes: "Single-mention. 'Not sure' anchored, exclusive." },
  ],
  "product-purchase-pipeline": [
    { type: "multi", stem: "Which of the following financial products do you plan to take out or apply for in the next 12 months? Select all that apply.", options: ["Current / checking account","Savings account or term deposit","Credit card","Personal loan","Mortgage or home loan","Car finance","Investment or brokerage account","Pension or retirement product","Insurance (life, home, or motor)","Buy Now Pay Later","None of these"], base: "All respondents.", randomize: true, analysis: "% planning each product (pick-any incidence); size the near-term demand pipeline.", placement: "Product block.", notes: "Pick-any. 'None of these' exclusive, anchored. Optional follow-up timing horizon (next 3 / 6 / 12 months) per selected product." },
  ],
  "onboarding-completion": [
    { type: "single", stem: "Thinking about the last time you tried to open a bank account online or in an app, did you complete the account opening?", options: ["Yes, I completed it","No, I started but did not finish","No, I gave up before starting the application"], base: "Respondents who attempted to open an account in the past [12] months.", randomize: false, analysis: "Claimed completion vs abandonment rate; triangulate with the analytics funnel completion %. Routes non-completers to reasons.", placement: "Onboarding/experience block.", notes: "Survey complements server-side funnel analytics. Non-completers route to abandonment reasons; completers to ease rating below." },
    { type: "scale", stem: "How easy or difficult was it to open your account?", scalePoints: ["Very easy","Somewhat easy","Neither easy nor difficult","Somewhat difficult","Very difficult"], base: "Recent openers who completed account opening.", randomize: false, analysis: "% Top-2-Box ease of opening; benchmark by channel. Pair non-completers with open-text abandonment reasons.", placement: "Onboarding/experience block, routed from completion.", notes: "For abandoners, capture reasons via a separate pre-coded + open item (ID verification failed, too many steps, asked for too much info, technical error, changed mind, etc.)." },
  ],
  "digital-banking-adoption": [
    { type: "grid", stem: "How often do you use each of the following to manage your banking?", scalePoints: ["Several times a day","About once a day","A few times a week","About once a week","A few times a month","Less often","Never"], subStems: ["Banking mobile app","Online banking via web browser","Branch in person","Telephone banking","ATM / cash machine"], base: "All respondents with a bank account.", randomize: true, analysis: "Adoption % (ever use = not 'Never') and frequency per channel. Derive segments: digital-only, hybrid, branch-reliant.", placement: "Channel/behaviour block.", notes: "Frequency grid; rows randomized. Segmentation rule defined in the analysis plan from app/web vs branch usage." },
  ],
  "banking-channel-mix": [
    { type: "grid", stem: "For each banking task below, which channel do you most prefer to use?", scalePoints: ["Mobile app","Online (web browser)","Branch in person","Call centre / phone","ATM / cash machine"], subStems: ["Checking balance or transactions","Making a payment or transfer","Paying in or withdrawing cash","Applying for a product (loan, card, account)","Getting help or resolving a problem","Financial advice or planning"], base: "All respondents with a bank account.", randomize: true, analysis: "Preferred channel distribution per operation (operation × channel); identify digital-resistant tasks. Optional follow-up on drivers per operation.", placement: "Channel/behaviour block.", notes: "Single preferred channel per row (operation × channel grid). Rows randomized. Add an open/pre-coded driver probe for key operations." },
  ],
  "payment-method-usage": [
    { type: "multi", stem: "Which of the following payment methods have you used in the past month? Select all that apply.", options: ["Physical debit or credit card","Mobile wallet (Apple Pay, Google Pay, etc.)","Cash","Bank transfer / instant payment","Direct debit","Online card payment","Buy Now Pay Later","Peer-to-peer app (e.g. PayPal, Venmo, Wise)","Cheque","None of these"], base: "All respondents.", randomize: true, analysis: "Pick-any usage incidence per method. Pair with a constant-sum on share of last-10 transactions by method, split by occasion (in-store / online / P2P).", placement: "Payments block.", notes: "'None of these' exclusive, anchored. Follow with a constant-sum allocation of last-N transactions across methods per occasion." },
  ],
  "fintech-usage": [
    { type: "multi", stem: "Which of the following fintech or neobank services do you currently use?", options: ["[Neobank A, e.g. Revolut]","[Neobank B, e.g. Monzo / N26]","[Wallet, e.g. PayPal]","[Local fintech C]","[Local fintech D]","Other fintech (please specify)","None of these"], base: "All respondents.", randomize: true, analysis: "Usage % by player. Pair with role-in-wallet (main vs secondary) and 5-pt likelihood-to-try (% T2B) among non-users.", placement: "Fintech/competitive block.", notes: "'None of these' exclusive, anchored. Users routed to role-in-wallet single; non-users to the try-intent scale below." },
    { type: "scale", stem: "How likely are you to try a fintech or neobank in the next 12 months?", scalePoints: ["Definitely will try","Probably will try","Might or might not","Probably will not","Definitely will not"], base: "Respondents not currently using any fintech / neobank.", randomize: false, analysis: "% Top-2-Box likelihood to try (propensity).", placement: "Fintech/competitive block, routed from usage.", notes: "Pairs with the usage item; measures switching/trial propensity among non-users." },
  ],
  "bnpl-usage": [
    { type: "single", stem: "How often have you used Buy Now Pay Later (e.g. Klarna, Clearpay, Afterpay) to spread the cost of a purchase in the past 12 months?", options: ["Never","Once","2-3 times","4-6 times","7 or more times"], base: "All respondents.", randomize: false, analysis: "Usage incidence (% any use) and frequency distribution. Routes users to the attitudinal battery.", placement: "Credit/payments block.", notes: "Ordered frequency scale, not randomized. Users and aware non-users route to the attitudinal battery below." },
    { type: "grid", stem: "How much do you agree or disagree with each statement about Buy Now Pay Later?", scalePoints: ["Strongly agree","Agree","Neither agree nor disagree","Disagree","Strongly disagree"], subStems: ["BNPL helps me manage my cash flow","BNPL is cheaper than using a credit card","I would use BNPL instead of taking a personal loan","BNPL makes it too easy to overspend","I fully understand the fees and penalties of BNPL","I trust BNPL providers as much as my bank"], base: "Respondents aware of BNPL (users and aware non-users).", randomize: true, analysis: "% Top-2-Box agreement per statement; contrast BNPL vs credit card vs personal loan positioning.", placement: "Credit/payments block, routed from BNPL usage.", notes: "Agreement grid; statements randomized. Includes one reverse-keyed item ('too easy to overspend')." },
  ],
  "trust-in-banks": [
    { type: "grid", stem: "How much do you trust each of the following to act in your best interest?", scalePoints: ["Trust completely","Trust a lot","Trust a moderate amount","Trust a little","Do not trust at all"], subStems: ["Traditional / high-street banks","Insurance companies","Fintechs and neobanks","The financial regulator","The financial system as a whole"], base: "All respondents.", randomize: true, analysis: "% Top-2-Box trust per institution type; sector-level trust index and gap vs the [Client] category.", placement: "Trust/attitudes block.", notes: "Sector-level trust scale; rows randomized. 5-pt trust anchors." },
  ],
  "fee-transparency": [
    { type: "grid", stem: "Thinking about your main bank, how much do you agree or disagree with each statement?", scalePoints: ["Strongly agree","Agree","Neither agree nor disagree","Disagree","Strongly disagree"], subStems: ["The fees and charges are clear and easy to understand","I am never hit with surprise or hidden charges","The fees I pay represent fair value for what I get","It is easy to find out what I will be charged before I act","My bank is upfront and honest about its charges"], base: "All respondents with a main bank.", randomize: true, analysis: "% Top-2-Box agreement per statement; fee-transparency/fairness index.", placement: "Trust/attitudes block.", notes: "Agreement battery on the main bank; statements randomized. 5-pt agree anchors." },
  ],
  "perceived-security": [
    { type: "grid", stem: "How confident are you that your money and personal data are kept safe when you bank through each of the following?", scalePoints: ["Very confident","Fairly confident","Neither confident nor unconfident","Not very confident","Not at all confident"], subStems: ["The mobile banking app","Online banking via web browser","In a branch","Over the phone","At an ATM / cash machine"], base: "All respondents who use the relevant channels.", randomize: true, analysis: "% Top-2-Box security confidence per channel; identify the weakest-trust channels. Pair with the fraud-concern battery and % citing security as a switching/adoption barrier.", placement: "Security/trust block.", notes: "Confidence grid per channel; rows randomized. Channels not used piped out per respondent." },
    { type: "grid", stem: "How much do you agree or disagree with each statement?", scalePoints: ["Strongly agree","Agree","Neither agree nor disagree","Disagree","Strongly disagree"], subStems: ["I worry about becoming a victim of fraud or a scam","I am concerned my bank could be hacked","Fear of fraud makes me cautious about online or app banking","Security concerns put me off using fintechs or neobanks","My bank would fully refund me if I were defrauded"], base: "All respondents.", randomize: true, analysis: "% Top-2-Box per statement (fraud-concern battery); % agreeing security deters digital/fintech use = security-as-barrier metric.", placement: "Security/trust block, paired with the channel-confidence grid.", notes: "Fraud-concern agreement battery; statements randomized. Reverse-keyed refund item for screening." },
  ],

  // ── Financial Needs & Wellbeing ──────────────────────────────────────────
  "financial-wellbeing": [
    { type: "scale", stem: "Here are some statements people have made about their financial situation. For each, please tell us how well it describes you or your situation.", scalePoints: ["Describes me completely","Describes me very well","Describes me somewhat","Describes me very little","Does not describe me at all"], attributes: ["I could handle a major unexpected expense","I am securing my financial future","Because of my money situation, I feel like I will never have the things I want in life","I can enjoy life because of the way I'm managing my money","I am just getting by financially","I am concerned that the money I have or will save won't last"], base: "All respondents", randomize: false, analysis: "CFPB IRT scoring to a 0–100 well-being score; report mean and distribution by segment. Use published response-category scoring tables; do not sum raw points. The last two items plus 'getting by' are reverse-keyed in framing.", placement: "Early in the questionnaire, before attitudinal/pressure items that could prime distress.", notes: "CFPB Financial Well-Being Scale 5-item short form. Item order fixed per instrument; a parallel 'how often' set (Never…Always) exists for the 10-item form. Provide the IRT scoring key for the exact item set/mode used." },
  ],
  "financial-literacy": [
    { type: "single", stem: "The next few questions check understanding of everyday money concepts. There are no trick questions — please answer without looking anything up.", subStems: ["Suppose you had €100 in a savings account and the interest rate was 2% per year. After 5 years, how much would you have if you left the money to grow?","Imagine the interest rate on your savings was 1% per year and inflation was 2% per year. After 1 year, how much would you be able to buy with the money in this account?","True or false? 'Buying a single company's stock usually provides a safer return than a stock mutual fund.'"], options: ["Compound interest: More than €102 / Exactly €102 / Less than €102 / Don't know / Refuse","Inflation: More than today / Exactly the same / Less than today / Don't know / Refuse","Diversification: True / False / Don't know / Refuse"], base: "All respondents", randomize: false, analysis: "Score correct answers 0–3 (correct: More than €102; Less than today; False). Report % correct per item, mean count, and % answering all three correctly. Keep 'Don't know' distinct from incorrect.", placement: "Mid-questionnaire, after behavioural items, before risk classification.", notes: "Lusardi–Mitchell 'Big Three', verbatim wording. Ask as three separate single-choice items; 'Don't know' and 'Refuse' must be explicit. Do not randomize — fixed canonical order. Localize currency." },
  ],
  "savings-emergency-fund": [
    { type: "single", stem: "If you lost your main source of household income today, roughly how long could your household cover essential expenses (housing, food, bills) using savings or money you could access quickly — without borrowing or selling long-term assets?", options: ["Less than 1 week","1 week to less than 1 month","1 month to less than 3 months","3 months to less than 6 months","6 months to less than 12 months","12 months or more","Don't know","Prefer not to say"], base: "All respondents", randomize: false, analysis: "Report distribution; key metric = % with at least 3 months' coverage (emergency-fund adequacy). Pair with the saving-regularity item for a saver typology.", placement: "In the savings/resilience block.", notes: "Months-bands format, privacy-preserving (no exact figures). Companion saving-incidence item recommended: 'In a typical month, does your household put money aside into savings? Always/Usually/Sometimes/Rarely/Never.'" },
  ],
  "budgeting-style": [
    { type: "scale", stem: "How well does each of these statements describe the way you usually manage your money?", scalePoints: ["Always","Often","Sometimes","Rarely","Never"], attributes: ["I keep track of what I spend","I set a budget and try to stick to it","I plan how to use money that comes in before it arrives","I use an app, spreadsheet or tool to manage my money","I check my account balance before making a purchase","I think about how a purchase fits my longer-term plans","I set money aside for known future bills before they are due"], base: "All respondents", randomize: true, analysis: "Factor/cluster analysis to derive money-management styles (organised planners, reactive spenders, tool-assisted, intuitive). Report mean per item and segment sizes.", placement: "Money-management block, before goals.", notes: "Behavioural frequency battery for factor analysis. A single planning-horizon item can be added (Next few days … Several years ahead)." },
  ],
  "financial-goals": [
    { type: "multi", stem: "Which of the following are financial goals you are actively working towards, or expect to in the next 1–3 years? Select all that apply.", options: ["Building or topping up an emergency fund","Paying down debt (loans, cards, overdraft)","Saving for a home deposit or buying property","Saving for retirement / later life","Saving for children's education","Saving for a major purchase (car, travel, wedding)","Starting or growing a business","Building investments / growing wealth","Leaving an inheritance or supporting family","Just keeping on top of day-to-day finances","None of these"], base: "All respondents", randomize: true, analysis: "Pick-any incidence per goal. Follow with priority ranking of selected goals (top 3) and a parallel life-events item. Cross-tab goals by life stage.", placement: "Goals & life-events block, after money-management.", notes: "Anchor 'None of these' at the end, exclusive. Companion ranking item: rank chosen goals 1–3. Companion life-events multi (next 1–3 years): moving home, having a child, marriage/partnership, divorce/separation, job change, retiring, inheritance, caring for a relative, none." },
  ],
  "attitude-to-credit": [
    { type: "scale", stem: "How much do you agree or disagree with each of the following statements about borrowing and credit?", scalePoints: ["Strongly agree","Agree","Neither agree nor disagree","Disagree","Strongly disagree"], attributes: ["It's OK to borrow money to buy things you want now and pay later","I would rather go without than buy something on credit","Using credit cards or loans is a normal part of managing money","Being in debt worries me a great deal","Spreading the cost of a purchase over time makes good financial sense","I avoid borrowing money whenever I possibly can","I am comfortable using 'buy now, pay later' to manage my spending"], base: "All respondents", randomize: true, analysis: "Mean and T2B agreement per item. Reverse-key credit-averse items, then build a credit-attitude index/segmentation (credit-friendly vs credit-averse). Report segment sizes.", placement: "Attitudes block, before debt-burden items.", notes: "Balanced battery with both pro-credit and credit-averse statements to control acquiescence. 5-point agree–disagree Likert." },
  ],
  "debt-burden": [
    { type: "single", stem: "Thinking about all your household's regular debt repayments (loans, credit cards, overdrafts, buy-now-pay-later — but not rent or mortgage unless you wish to include it), roughly what share of your monthly take-home income goes towards them?", options: ["We have no debt repayments","Less than 10%","10% to under 25%","25% to under 40%","40% to under 50%","50% or more","Don't know","Prefer not to say"], base: "All respondents", randomize: false, analysis: "Distribution of repayment-to-income bands; flag over-indebtedness at ≥40%. Combine with difficulty indicators for an over-indebtedness index.", placement: "Debt block; sensitive — place after rapport-building, allow opt-out.", notes: "Income-share bands, privacy-preserving. Pair with two difficulty items: (1) keeping up with bills — Without difficulty / Minor difficulties / A constant struggle / Falling behind; (2) missed/late payment in last 12 months — Yes / No / Prefer not to say. Key metrics: % struggling, % missed payment in 12M." },
  ],
  "risk-tolerance": [
    { type: "single", stem: "Investing involves a trade-off between possible returns and the risk of losses. Which of the following best describes how you would prefer to invest a meaningful sum of your own money?", options: ["I want to protect my money and accept very low returns to avoid any loss","I prefer mostly safe investments and can accept small ups and downs for slightly higher returns","I want a balance of safety and growth, and can accept moderate ups and downs","I aim for higher growth and can accept significant ups and downs in value","I want maximum long-term growth and can accept large losses for the chance of high returns"], base: "All respondents (or those with/considering investments)", randomize: false, analysis: "Classify conservative → aggressive (1–5). Pair with a loss-reaction scenario and an investment-horizon item to form a composite MiFID-style risk profile; never classify on a single item alone for suitability.", placement: "Investment/risk block.", notes: "MiFID-style risk-tolerance ladder; ordered options, do not randomize. Companion scenario: 'If your investment fell 20% in a few months, would you — Sell everything / Sell some / Do nothing / Buy more.' Combine willingness (attitude) with capacity (horizon, ability to bear loss)." },
  ],
  "retirement-preparedness": [
    { type: "grid", stem: "Thinking about your retirement or later life, please answer the following.", subStems: ["How prepared do you feel financially for retirement?","How confident are you that you will have enough money to live comfortably throughout retirement?"], scalePoints: ["Not at all","Slightly","Moderately","Very","Completely"], base: "All non-retired respondents (route retired respondents to a reduced set).", randomize: false, analysis: "Report % T2B prepared and % T2B confident. Cross with actual provision (count and Pillar II/III incidence). Flag a 'preparedness gap' = low provision but high confidence, and the reverse.", placement: "Retirement block, after savings and before advice-seeking.", notes: "Two 5-pt self-rating scales (preparedness, confidence). Pair with a pick-any provision inventory using the three-pillar framework (State pension / Workplace pension / Private pension / Other long-term investments / Property / None / Don't know). Localize pillar terminology." },
  ],
  "protection-gap": [
    { type: "multi", stem: "Which of the following types of insurance or financial protection do you (or your household) currently have? Select all that apply.", options: ["Life insurance","Critical illness cover","Income protection / disability cover","Health / medical insurance","Home / contents insurance","Mortgage protection","Funeral / final-expenses cover","None of these","Don't know"], base: "All respondents", randomize: true, analysis: "Coverage incidence per type. Cross against a needs profile (dependents, mortgage, sole earner) to compute unmet protection need: % with dependents/mortgage but no life or income protection = protection gap per risk.", placement: "Protection block; precede with a short dependents/financial-responsibilities screen.", notes: "Pick-any coverage vs need. 'None of these' and 'Don't know' fixed at end, exclusive. Companion needs screen: dependents on your income? mortgage or major debt? main or sole earner? — used to define who needs each cover." },
  ],
  "financial-anxiety": [
    { type: "scale", stem: "Thinking about your personal finances, how much do you agree with each of the following?", scalePoints: ["Strongly agree","Agree","Neither agree nor disagree","Disagree","Strongly disagree"], attributes: ["I feel confident about managing my day-to-day finances","I feel confident about making bigger financial decisions","Thinking about my finances makes me feel anxious","I worry about money most days","I feel in control of my financial situation","I often feel stressed when dealing with money matters"], base: "All respondents", randomize: true, analysis: "Report % T2B for confidence items and % T2B for anxiety items separately (do not net). Build a confidence index and an anxiety index; correlate with the CFPB well-being score.", placement: "Adjacent to the well-being score, ideally just after it.", notes: "Two interleaved 5-pt Likert sub-scales (confidence, anxiety). Anxiety items reverse-keyed relative to confidence." },
  ],
  "advice-seeking": [
    { type: "grid", stem: "Where do you turn for help when making financial decisions, and how much do you trust each source?", subStems: ["Day-to-day money management","Borrowing or taking on debt","Saving and investing","Retirement or long-term planning","Insurance and protection"], scalePoints: ["Do not use","Use – low trust","Use – moderate trust","Use – high trust"], attributes: ["A professional financial adviser","My bank or building society","Family or friends","My employer or workplace scheme","Online tools, comparison sites or robo-advisers","Social media, forums or online communities","News, money websites or the press","I make these decisions on my own"], base: "All respondents", randomize: true, analysis: "Source usage incidence per decision type (read across) and trust rating per source. Identify dominant channels by decision type and an overall trust ranking of sources. Cross with literacy and well-being.", placement: "Advice block, near the end before classification.", notes: "Grid crossing decision types (rows) × sources (columns), capturing both usage and trust in one scale. 'I make these decisions on my own' fixed at end. For shorter surveys, split into a source pick-any per decision plus a separate trust-by-source rating." },
  ],
};
