// GENERAT din mockups/vadim.html — catalogul de indicatori în stil
// pamflet vadimist („Tribunul 3000"). Numele originale rămân în engleză;
// aici sunt doar descrierile-sentință și rubricile gazetei, pe categorii.
// Regenerare: scripts în scratchpad (extract-vadim.js) sau manual.

import type { IndicatorCategory } from "./indicators";

export interface VadimRubric {
  /** „RUBRICA I" … — numărul de gazetă al categoriei */
  numar: string;
  /** Titlul-pamflet al rubricii */
  titlu: string;
  /** Motto-ul rubricii */
  motto: string;
}

export const VADIM_RUBRICI: Record<IndicatorCategory, VadimRubric> = {
  "Brand Health & Equity": {
    numar: "RUBRICA I",
    titlu: "Sănătatea brandului, domnilor!",
    motto: "Starea națiunii de marcă, de la primul strigăt de notorietate până la zestrea cântărită la gram.",
  },
  "Usage & Attitudes (U&A)": {
    numar: "RUBRICA II",
    titlu: "Năravuri și apucături",
    motto: "Cine, ce, cât și mai ales de ce — obiceiurile neamului, puse la dosar.",
  },
  "Purchase Behaviour & Pricing": {
    numar: "RUBRICA III",
    titlu: "Banul, ochiul dracului",
    motto: "Aici se despart patrioții de zgârciți: totul despre preț, fără perdea.",
  },
  "Concept & Product Testing": {
    numar: "RUBRICA IV",
    titlu: "Judecata de apoi a produselor",
    motto: "Concepte intră, sentințe ies. Aici nu se fentează nimic.",
  },
  "Customer Experience & Satisfaction": {
    numar: "RUBRICA V",
    titlu: "Doleanțele poporului",
    motto: "Registrul de jalbe și mulțumiri, ținut la zi cu sfințenie.",
  },
  "Advertising & Communications": {
    numar: "RUBRICA VI",
    titlu: "Propaganda și tribuna",
    motto: "Reclama e sufletul comerțului — dar sufletul trebuie verificat, domnilor.",
  },
  "UX Research": {
    numar: "RUBRICA VII",
    titlu: "Chinurile utilizatorului",
    motto: "Calvarul omului în fața butoanelor, documentat științific.",
  },
  "Banking & Payments": {
    numar: "RUBRICA VIII",
    titlu: "Bancherii, domnilor!",
    motto: "Unde sunt banii neamului și pe la ce ghișee umblă.",
  },
  "Financial Needs & Wellbeing": {
    numar: "RUBRICA IX",
    titlu: "Sărăcia și nevoile neamului",
    motto: "Portofelul poporului, ascultat cu stetoscopul.",
  },
};

/** Descrierea-sentință a fiecărui indicator, cheiată pe id. */
export const VADIM_INDICATOR_RO: Record<string, string> = {
  "tom-awareness": "Zici «categoria», și un singur nume țâșnește primul din capul poporului — acela e stăpânul minții, restul fac figurație",
  "spontaneous-awareness": "Câte mărci poți înșira din memorie, fără să-ți sufle nimeni — ce nu-ți amintești singur nu există, domnilor",
  "aided-awareness": "Abia când îți punem lista sub nas zici «a, da, o știu!» — recunoașterea la vedere, ultima treaptă a notorietății",
  "brand-salience": "Marca vrednică răsare singură în minte la orice ocazie — la sete, la drum, la necaz — nu doar când o strigi pe nume",
  "brand-familiarity": "Una e s-o știi din auzite, alta s-o cunoști ca pe propriul dosar — aici cântărim cât de bine simți că o cunoști",
  "brand-consideration": "A prins loc pe lista scurtă a cumpărăturii, ori nici nu intră în discuție? La palat ajung doar candidatele serioase",
  "brand-preference": "Dintre toate candidatele de pe lista scurtă, una singură primește votul dumitale — restul, la urne data viitoare",
  "brand-trial": "Ai încercat-o măcar o dată în viață, fie și pe furiș? Prima gustare desparte vorba de faptă",
  "brand-usage": "Ai folosit-o de curând — anul ăsta, luna asta, săptămâna asta — ori ești client doar cu numele, din amintiri?",
  "bumo": "Marca la care te întorci cel mai des, ciorba de-acasă a categoriei — celelalte rămân aventuri de-o vară",
  "brand-loyalty": "Rămâi la ea și când concurența îți face cu ochiul, ori fugi la prima reducere? Fidelitatea se măsoară la ispită",
  "brand-advocacy": "N-o ții pentru dumneata: o recomanzi rudelor, vecinilor și națiunii întregi, ca de la tribună",
  "brand-image": "Ce etichete îi lipește poporul pe frunte — harnică, scumpă, de nădejde? Portretul-robot al mărcii, față în față cu concurența",
  "brand-affinity": "Nu doar o folosești, o iubești: «asta e de-a noastră», zice inima — atașamentul care nu se măsoară în lei",
  "brand-trust": "Promite și se ține de cuvânt, ori promite ca politicienii în campanie? Încrederea se câștigă greu și se pierde într-o seară",
  "brand-equity-index": "Toată zestrea mărcii — faimă, sens, unicitate — topită într-o singură cifră și cântărită ca aurul dacilor",
  "brand-funnel-conversion": "Te știe tot poporul, dar la casă ajung trei oameni? Numărăm la fiecare vamă a pâlniei câți merg mai departe și pe unde curge",
  "share-of-voice": "Din toată gălăgia reclamelor din categorie, cât e glasul mărcii dumitale? Cine strigă mai tare azi vinde mai mult mâine",
  "distinctive-brand-assets": "Ascundem numele și arătăm doar fularul roșu, sigla, culoarea: dacă poporul te ghicește și-așa, ai avere; dacă nu, ai fluturat degeaba",
  "sustainability-perception": "Cinstită și verde de-adevăratelea, ori doar vopsită pentru televizor? Vedem și dacă poporul ar plăti în plus pentru virtute",
  "category-penetration": "Câți din popor au căzut în patima categoriei",
  "usage-frequency": "Cât de des, domnilor: zilnic, duminica, ori la Paștele cailor?",
  "usage-occasions": "Când anume: la cafea, la telejurnal sau la supărare?",
  "weight-of-usage": "Consumatori de elită, de mijloc și de duminică",
  "brand-repertoire": "Suita de mărci a fiecărui cetățean — care intră la palat, care așteaptă la poartă",
  "share-of-wallet": "Cât din portofel îi dai ei, și cât împrăștii prin concurență",
  "habits-practices": "Obiceiurile neamului, de la stră-străbunici citire",
  "category-attitudes": "Ce zice poporul despre categorie, cu mâna pe inimă",
  "needs-motivations": "Ce-l arde pe om cu adevărat, în adâncul sufletului său",
  "jobs-to-be-done": "Treaba pentru care ai tocmit produsul — să muncească, nu să lenevească",
  "path-to-purchase": "Drumul crucii, de la prima ispită până la casa de marcat",
  "channel-usage": "De unde târguiește românul: din piață, de la boutique ori de pe net",
  "media-consumption": "Ce privește poporul la televizor, în loc să citească pamflete",
  "lapsing-churn-reasons": "De ce te-au părăsit? Foștii clienți depun mărturie la tribună",
  "purchase-intention": "Cumperi sau nu cumperi? Răspunde, nu te codi!",
  "purchase-triggers": "Scânteia care aprinde portofelul",
  "purchase-barriers": "Zidurile Bastiliei dintre om și produs",
  "trial-intent": "Ai încerca o dată, măcar de gura lumii?",
  "repeat-purchase-intent": "Te mai întorci, ori a fost amor de-o vară?",
  "willingness-to-pay": "Cât scoți din buzunar fără să verși o lacrimă de patriot",
  "van-westendorp": "Domnul Van Westendorp, olandez serios, află exact unde te doare prețul",
  "gabor-granger": "Întindem prețul ca elasticul și notăm când plesnește răbdarea poporului",
  "value-for-money": "Face banii, ori e jaf în plină zi, ca la drumul mare?",
  "promo-responsiveness": "Cum sare românul la reduceri, ca știuca la momeală",
  "conjoint-analysis": "Alegeri grele, domnilor: ori ieftin, ori bun — ca la vot",
  "overall-liking": "Îți place sau nu-ți place? Simplu ca bună ziua!",
  "likes-dislikes": "Ce lăudăm în piața mare și ce trimitem la topit",
  "uniqueness": "Unic ca Tribunul, ori copie la indigo?",
  "relevance": "Îți trebuie cu adevărat, sau doar așa, de fală?",
  "believability": "Te credem, ori am mai auzit noi promisiuni electorale?",
  "comprehension": "S-a înțeles, ori vorbim păsărește ca diplomații?",
  "jar-scales": "Nici prea-prea, nici foarte-foarte: fix cât trebuie",
  "paired-preference": "Duel în zori de zi: două produse intră, unul singur iese",
  "expected-frequency": "Cât de des l-ai lua: săptămânal, ori o dată pe mandat?",
  "price-perception-concept": "La prețul ăsta: pomană cerească sau tâlhărie la drumul mare?",
  "kano-model": "Domnul Kano desparte moftul de necesitate, ca grâul de neghină",
  "maxdiff": "Cel mai iubit și cel mai hulit, ca în politica dâmbovițeană",
  "turf": "Cu ce combinație de produse cucerim toată patria, județ cu județ",
  "nps": "Ne recomanzi la neamuri, ori ne faci de râs în târg? Notă de la 0 la 10!",
  "csat": "Mulțumit, cetățene, ori scrii memorii la gazetă?",
  "ces": "Cât te-ai canonit, ca Meșterul Manole, pentru o nimica toată",
  "repurchase-intention": "Mai semnezi un mandat cu noi, ori treci în opoziție?",
  "complaint-incidence": "Jalbe primite, jalbe rezolvate: contabilitatea supărării naționale",
  "key-driver-importance": "Unde se câștigă și unde se pierde inima clientului",
  "servqual": "Servit ca la curtea regală, ori ca la ghișeul din anii '90?",
  "ad-recall": "Ți-a rămas reclama în cap, ori a intrat pe-o ureche și-a ieșit pe cealaltă?",
  "ad-recognition": "O recunoști dintr-o mie, ca pe fularul roșu?",
  "brand-linkage": "Ții minte reclama, dar știi și a cui e, istețule?",
  "message-takeout": "Ce-a priceput poporul din discurs — că una zici și alta se aude",
  "persuasion": "Te-a întors reclama din drum, ca un discurs bine țintit?",
  "ad-likeability": "Aplauze la scenă deschisă, ori huiduieli din galerie?",
  "ad-distinctiveness": "Iese din plutonul de reclame, ori defilează la grămadă cu toate?",
  "call-to-action": "După reclamă treci la fapte, ori rămâi la vorbe, ca dânșii?",
  "task-success": "Câți ajung la liman și câți se îneacă la mal",
  "time-on-task": "Cât durează isprava: cât un discurs, ori cât o legislatură?",
  "error-rate": "Câte boacăne pe cap de utilizator",
  "sus": "Nota poporului pentru sistem: zece întrebări, fără pile",
  "seq": "O singură întrebare, ca la spovedanie: greu a fost, fiule?",
  "umux-lite": "Procesul scurt: două întrebări și sentința",
  "umux": "Procesul întreg, cu toată comisia de față",
  "first-click": "Primul click: la țintă, ori în lături ca vânătorul de duminică?",
  "findability": "Găsești ce cauți, ori te rătăcești ca-n Bărăgan pe timp de noapte?",
  "learnability": "Cât de iute prinde poporul șmecheria",
  "nasa-tlx": "Cât te-a stors efortul — măsurat de NASA, nu de vecina de palier",
  "desirability": "Spune-i produsului în față ce simți: cuvintele pe masă!",
  "feature-adoption": "Câți au îmbrățișat noutatea, și câți o ocolesc ca pe recensământ",
  "engagement": "Se lipește lumea de produs cum se lipește poporul de televizor?",
  "retention-churn": "Câți rămân credincioși, și câți trădează pe lună — cu nume și prenume",
  "heart-framework": "Cardiograma produsului, făcută — cică — la Google",
  "accessibility": "Pentru tot poporul, domnilor — nimeni nu rămâne pe dinafară!",
  "digital-literacy": "Cât de bine se descurcă românul cu drăcia asta de internet",
  "main-bank-share": "Banca de suflet: acolo unde-ți ții și banii, și nervii",
  "bank-switching-intent": "Fugi la altă bancă, ori rămâi pe baricadă până la capăt?",
  "switching-triggers-barriers": "Ce te-ar face să-ți iei banii și să trântești ușa de se-aude-n sucursală",
  "cross-sell-intent": "Îți mai vinde banca un produs, ori ți-ai învățat lecția?",
  "consolidation-intent": "Aduni toți banii sub un singur steag, ca un adevărat unificator?",
  "product-purchase-pipeline": "Ce-ți mai iei de la bancă până la anul, cu voia Domnului și a dobânzii",
  "onboarding-completion": "Câți deschid contul până la capăt, și câți dezertează la primul act cerut",
  "digital-banking-adoption": "Banca din buzunar: cât o folosește națiunea, cu degetul mare",
  "banking-channel-mix": "La ghișeu ca pe vremuri, ori pe telefon ca tineretul?",
  "payment-method-usage": "Cash ca bunicul, card ca nepotul, telefon ca strănepotul",
  "fintech-usage": "Băncile astea noi, fără sediu și fără cravată — le-ncredințezi agoniseala?",
  "bnpl-usage": "Cumperi acum, plătești mai târziu — dulce la gust, amară la scadență",
  "trust-in-banks": "Mai crede poporul în bănci, ori doarme cu banii la saltea, ca strămoșii?",
  "fee-transparency": "Comisioanele: la vedere, ca oamenii cinstiți, ori pitite ca dosarele?",
  "perceived-security": "Doarme românul liniștit, ori visează hackeri și pungași?",
  "financial-wellbeing": "Starea de bine la portofel: notă de la jale la huzur",
  "financial-literacy": "Câtă carte financiară a citit poporul — sincer acum, fără copiuțe",
  "savings-emergency-fund": "Bani albi pentru zile negre: cât ține sacul?",
  "budgeting-style": "Cine-i contabil-șef acasă: caietul, aplicația, ori soacra?",
  "financial-goals": "Visurile neamului: casă, mașină și nuntă ca în povești",
  "attitude-to-credit": "Te împrumuți cu inima ușoară, ori numai cu cuțitul la os?",
  "debt-burden": "Câtă datorie duce românul în spinare fără să crâcnească",
  "risk-tolerance": "Joci la bursă ca la ruletă, ori păstrezi cu sfințenie, ca strămoșii?",
  "retirement-preparedness": "Pregătit de pensie, ori te lași în grija milei statului?",
  "protection-gap": "Asigurat ca lumea bună, ori descoperit ca hotarul patriei?",
  "financial-anxiety": "Dormi liniștit pe banii tăi, ori te trezești noaptea în sudori?",
  "advice-seeking": "Pe cine asculți la bani: banca, cumătrul, ori Tribunul?",
};
